# Project: Proyecto 1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o funciones.o
LINKOBJ  = main.o funciones.o
LIBS     = -L"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/lib" -L"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/include" -I"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/include" -I"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"Z:/home/david-murillo/Documentos/Documentos/Universidad/5-SEMESTRE/PROGRAMACION-3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Proyecto 1.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

funciones.o: funciones.c
	$(CC) -c funciones.c -o funciones.o $(CFLAGS)
